# **Pre-Built Methods in Numpy to create Arrays**

## **3. np.linspace()**

In [5]:
import numpy as np

arr = np.linspace(0, 10, 10) # linspace(startPoint, endPoint, PartitionNum)
print(arr)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


# **4. np.zeros()**

In [18]:
zeroArr = np.zeros([3,3])
print(zeroArr)
print((zeroArr.dtype))
newZeroArr = zeroArr.astype(np.int64)
print(newZeroArr)
print((newZeroArr.dtype))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64
[[0 0 0]
 [0 0 0]
 [0 0 0]]
int64


## **5. np.ones()**

In [23]:
onesArr = np.ones([4,3], dtype=np.int64)
print(onesArr)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [24]:
onesArr = np.ones(4, dtype=np.int64)
print(onesArr)

[1 1 1 1]


## **6. np.full()**

In [30]:
fullArr = np.full([4,6], 7)
print(fullArr)

[[7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]]


## **7. np.flatten()**

In [56]:
# arr2D = np.array([[2, 2, 2, 2], [2, 2, 2, 2], [2, 2, 2, 2]])
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9],[10,20,30]])
print(arr2D)
print(arr2D.size)

flattenArr = arr2D.flatten()
print(flattenArr)
print(flattenArr.size)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]]
12
[ 1  2  3  4  5  6  7  8  9 10 20 30]
12


## **8. np.ravel()**

In [55]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9],[10,20,30]])
print(arr2D)
print(arr2D.size)

flatArr = arr2D.ravel()
print(flatArr)
print(flatArr.size)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]]
12
[ 1  2  3  4  5  6  7  8  9 10 20 30]
12


# **Difference b/w flatten and ravel method - **

In [59]:
print(flatArr)
print(flattenArr)

flatArr[0] = 55
# flattenArr[0] = 55

print(flatArr)
# print(flattenArr)
print(arr2D)

[55  2  3  4  5  6  7  8  9 10 20 30]
[55  2  3  4  5  6  7  8  9 10 20 30]
[55  2  3  4  5  6  7  8  9 10 20 30]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]]


In [45]:
flatArr = arr2D[arr2D >= 5]
print(flatArr)
print(arr2D)

[ 5  6  7  8  9 10 20 30]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]]


In [48]:
flattenArr = arr2D[arr2D >= 5]
print(flattenArr)
print(arr2D)

[ 5  6  7  8  9 10 20 30]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]]


## **9. np.reshape()**

In [68]:
arr = np.arange(20, 44)
print(arr)
print(arr.size)

new2DArr = arr.reshape(8,3)
print(new2DArr)

new3DArr = arr.reshape(3,2,4)
print(new3DArr)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43]
24
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]
 [38 39 40]
 [41 42 43]]
[[[20 21 22 23]
  [24 25 26 27]]

 [[28 29 30 31]
  [32 33 34 35]]

 [[36 37 38 39]
  [40 41 42 43]]]
