# **Pre-Built Methods in Numpy to create Arrays**

## **10. np.random.rand()**

In [10]:
import numpy as np

# randomNum = np.random.rand(7) * 100
# print(randomNum)

# random2DArr = np.random.rand(4,3) * 10
# print(random2DArr)

# random3DArr = np.random.rand(2, 3, 4) * 10
# print(random3DArr)

[[[7.33391073 4.98920475 0.41666453 8.39408294]
  [6.32983476 7.30520194 9.26846234 7.25965655]
  [5.87960883 5.04341178 2.74806446 1.69128253]]

 [[9.3299959  1.82518823 5.65310817 0.12313792]
  [8.0190283  0.22284263 7.00743651 0.21321701]
  [4.4461129  3.22021752 0.10316616 0.21151966]]]


## **11. np.random.randn()**

In [14]:
# arr = np.random.randn(5)
# print(arr)

# arr2D = np.random.randn(3,5)
# print(arr2D)

# arr3D = np.random.randn(3, 3,5)
# print(arr3D)

[[[-0.16431193 -1.03958549  2.28800033  0.29540737  0.03793367]
  [-2.20883052 -0.04378214  0.46946218 -1.47641525 -1.23366771]
  [ 2.18813784 -0.4222315   0.14187389 -0.59856094  1.03154801]]

 [[-1.02076402 -0.79615026  0.62292787 -0.86584603  0.95271419]
  [ 1.00751154  1.5881975  -0.25624531 -0.34898107 -0.70928693]
  [-1.84806339  0.04899288  0.71394402  0.31920857 -0.01821048]]

 [[ 1.21764689  0.75857268  0.50928107 -0.50910611 -0.58991827]
  [-2.21045964  1.82057884  0.07633102 -0.5430278  -0.64932403]
  [-0.28494588 -1.06407627 -0.11092937 -0.05398799 -1.87076023]]]


# **12. np.random.randInt()**

In [16]:
arr = np.random.randint(1, 10, [5,4])
print(arr)

[[1 1 3 6]
 [2 7 3 3]
 [6 3 9 1]
 [3 8 1 3]
 [7 3 8 9]]


## **13. np.eye()**

In [23]:
idenMat = np.eye(5, dtype=np.int64)
print(idenMat)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


## **14. np.identity()**

In [22]:
idMat = np.identity(5, dtype=np.int64)
print(idMat)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


# **Fancy Index in Mult-D nDimArray**

In [50]:
arr2D = np.arange(1,37).reshape(6,6)
# print(arr2D)

# new2DArr = arr2D[[0], [1,3,5]]
# new2DArr = arr2D[[3], [0,3,4]]
# new2DArr = arr2D[[[2],[3],[5]], [[0,1],[3,4],[1,2]]]
# new2DArr = arr2D[[[5],[3],[1]], [[-1,-2],[-3,-4],[1,0]]]

# print("\n")
# print(new2DArr)


arr3D = arr2D.reshape(2,3,6)
print(arr3D)

# new3DArr = arr3D[[1], [1], [0,2,4]]
new3DArr = arr3D[[[[1]], [[0]]], [[[0],[1]], [[1],[2]]], [[[2,3], [2,3]], [[2,3], [2,3]]]]

print("\n")
print(new3DArr)


[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]
  [13 14 15 16 17 18]]

 [[19 20 21 22 23 24]
  [25 26 27 28 29 30]
  [31 32 33 34 35 36]]]


[[[21 22]
  [27 28]]

 [[ 9 10]
  [15 16]]]


# **Broadcasting & Vectorization**

In [41]:
# Broadcasting -

## **Vectorization**

In [60]:
randArr = np.random.randint(1, 10, size=10)
print(randArr)
randomArr = np.random.randint(1,5, size=5)
print(randomArr)

newArr = randArr * 5
print(newArr)

newnewArr = randArr * randArr
print(newnewArr)

[4 5 5 8 1 3 9 1 6 3]
[2 1 3 1 3]
[20 25 25 40  5 15 45  5 30 15]
[16 25 25 64  1  9 81  1 36  9]


In [56]:
li = [1,2,3,4,5,6]

# newLi = li * li
# print(li)
# print(newLi)

TypeError: can't multiply sequence by non-int of type 'list'