# **Pre-Built Methods in Numpy to create Arrays**

In [8]:
prodIn = [10,20,15,16,4,8]
prodInSet = (10,20,15,16,4,8)
print(prodIn)
print(type(prodIn))

[10, 20, 15, 16, 4, 8]
<class 'list'>


In [3]:
# pip install numpy

### **1. np.array()**

In [9]:
import numpy as np

inventory = np.array(prodInSet)
print(inventory)
print(type(inventory))

[10 20 15 16  4  8]
<class 'numpy.ndarray'>


### **2. np.arange()**

In [10]:
rangeArr = np.arange(51, 101)
print(rangeArr)
print(type(rangeArr))

[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]
<class 'numpy.ndarray'>


In [12]:
rangeArr = np.arange(2, 101, 2)
print(rangeArr)
print(type(rangeArr))

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
<class 'numpy.ndarray'>


In [15]:
reverse5Table = np.arange(50, 4, -5)
print(reverse5Table)

[50 45 40 35 30 25 20 15 10  5]


## **Creating Multi-D Array **

In [25]:
arr2D = np.array([[[1,2,3,4], [5,6,7,8], [9,10,11,12]], [[1,2,3,4], [5,6,7,8], [9,10,11,12]]])
print(arr2D)
np.ndim(arr2D)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


3

In [57]:
arr = np.array([1,2,3,4,5,6])
# print(arr[2])
# len(arr)
# np.size(arr)

li = [1,2,3,4,5,6]
# newArr = li[1:4]    # li[startIndex:endIndex]   (end is humesha -2)
# newArr, li

# newArr = li[:4]
# newArr, li

# revLi = li[::-1]
# revLi, li

# newArr = arr[4:0:-1]
# newArr, arr


# newArr = li[1::2]
# newArr, li


# newArr = arr[1::2]
# newArr, li

# newArr = li[1,3,6]
# newArr, li



# Fancy Indexing -
newArr = arr[[1,3,5]]
newArr, arr

(array([2, 4, 6]), array([1, 2, 3, 4, 5, 6]))

In [38]:
arr2D = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])

# arr2D[0][4]
# arr2D[1][1]
# np.size(arr2D)
# np.shape(arr2D)

np.int64(2)

In [40]:
arr3D = np.array([[[1,2,3,4,5,6],[1,2,3,4,5,6]],
                  [[1,2,3,4,5,6],[1,2,3,4,5,6]],
                  [[1,2,3,4,5,6],[1,2,3,4,5,6]]])

arr3D[0][0][3]

np.int64(4)

In [59]:
# Boolean Masking
li = [10,20,11,22,101,102]

# newLi = li[li%2 == 0]
# newLi, li

arr = np.array(li)
newArr = arr[arr%2 == 0]

newArr, arr

(array([ 10,  20,  22, 102]), array([ 10,  20,  11,  22, 101, 102]))